from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('analytics/', views.Brokerlist.as_view(), name="graph"),
    path('clarksonyearweek', views.Clarksonyearweek.as_view(),
         name="clarkson_year_week"),
    path('clarksonspotfixture/<int:year>/<int:week>',
         views.ClarksonspotfixtureView.as_view(), name='spot-fixture'),
    path('clarksontimefixture/<int:year>/<int:week>',
         views.ClarksontimefixtureView.as_view(), name='time-fixture'),
    path('clarksonspotass1/<int:year>/<int:week>',
         views.Clarksonspotassesment1View.as_view(), name='clarkson-spot-assessmentone'),
    path('clarksonspotass2/<int:year>/<int:week>',
         views.Clarksonspotassesment2View.as_view(), name='clarkson-spot-assessmenttwo'),
    path('clarksontimeass/<int:year>/<int:week>',
         views.ClarksontimeassesmentView.as_view(), name='clarkson-timeass'),
    path('gibsonyearweek', views.Gibsonyearweek.as_view(), name='Gibson_year_week'),
    path('gibsonspotfixture/<int:year>/<int:week>',
         views.GibsonspotfixtureView.as_view(), name='gibson_spotfixture'),
    path('gibsontimefixture/<int:year>/<int:week>',
         views.GibsontimefixtureView.as_view(), name='gibson_timefixture'),
    path('gibsonspotass/<int:year>/<int:week>',
         views.GibsonspotassView.as_view(), name='gibson_spotassessment'),
    path('gibsontimeass/<int:year>/<int:week>',
         views.GibsontimeassView.as_view(), name='gibson_timeassessment'),
    path('steemyearweek', views.Steemyearweek.as_view(), name='steem_year_week'),
    path('steemspotfixture/<int:year>/<int:week>',
         views.SteemspotfixtureView.as_view(), name='steem_spotfixture'),
    path('steemtimefixture/<int:year>/<int:week>',
         views.SteemtimefixtureView.as_view(), name='steem_timefixture'),
    path('steemspotass/<int:year>/<int:week>',
         views.SteemspotassView.as_view(), name='steem_spotassessment'),
    path('steemtimeass/<int:year>/<int:week>',
         views.SteemtimeassView.as_view(), name='steem_timeassessment'),
    path('fearngasyearweek', views.Fearngasyearweek.as_view(),
         name='fearngas_year_week'),
    path('fearngasspotfixture/<int:year>/<int:week>',
         views.FearngasspotfixtureView.as_view(), name='fearngas_spotfixture'),
    path('fearngastimefixture/<int:year>/<int:week>',
         views.FearngastimefixtureView.as_view(), name='fearngas_timefixture'),
    path('fearngasspotassement/<int:year>/<int:week>',
         views.FearngasspotassementView.as_view(), name='fearngas_spotassessment'),
    path('braemaryearweek', views.Braemaryearweek.as_view(),
         name='braemar_year_week'),
    path('braemarspotfixture/<int:year>/<int:week>',
         views.BraemarspotfixtureView.as_view(), name='braemar_spotfixture'),
    path('braemarspotassesment/<int:year>/<int:week>',
         views.BraemarspotassesmentView.as_view(), name='braemar_spotassesment'),
    path('braemartimefixture/<int:year>/<int:week>',
         views.BraemartimefixtureView.as_view(), name='braemar_timefixture'),
    path('braemartimeassesment1/<int:year>/<int:week>',
         views.Braemartimeassesment1View.as_view(), name='braemar_timeassesment1'),
    path('braemartimeassesment2/<int:year>/<int:week>',
         views.Braemartimeassesment2View.as_view(), name='braemar_timeassesment2'),
    path('<name>/<int:year>/<int:week>', views.BrokerYearWeekDate.as_view(),
         name='broker_per_year_week_date_range'),
    path('sendmail', views.send_email, name='send_mail'),
    path('login', views.login, name="user_login")
]
