# Generated by Django 2.2.3 on 2019-07-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0003_auto_20190730_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
