# Generated by Django 2.2.3 on 2019-07-30 18:40

from django.db import migrations, models
import text_extraction.validators


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0004_auto_20190730_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf/', validators=[text_extraction.validators.validate_file_extension]),
        ),
    ]
