# Generated by Django 2.2.3 on 2019-07-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0005_auto_20190731_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clarksontimefixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesed12month', models.TextField()),
                ('thisweekMonthly', models.TextField()),
                ('thisweekDaily', models.TextField()),
                ('lastweekMonthly', models.TextField()),
                ('lastweekDaily', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'Clarksontimefixture',
            },
        ),
    ]
