# Generated by Django 2.2.3 on 2019-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0006_clarksontimefixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clarksonspotfixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.TextField()),
                ('CBM', models.TextField()),
                ('Cargo', models.TextField()),
                ('Voyage', models.TextField()),
                ('Laycan', models.TextField()),
                ('Rate', models.TextField()),
                ('Charterer', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'Clarksonspotfixture',
            },
        ),
    ]
