# Generated by Django 2.2.3 on 2019-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0007_clarksonspotfixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clarksonspotass1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesed', models.TextField()),
                ('thisweekMonthly', models.TextField()),
                ('thisweekDaily', models.TextField()),
                ('lastweekMonthly', models.TextField()),
                ('lastweekDaily', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clarksonspotass2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weeklyfrieghtass', models.TextField()),
                ('thisweek', models.TextField()),
                ('lastweek', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
