# Generated by Django 2.2.3 on 2019-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0008_clarksonspotass1_clarksonspotass2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clarksontimeass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.TextField()),
                ('CBM', models.TextField()),
                ('Cargo', models.TextField()),
                ('Area', models.TextField()),
                ('Period', models.TextField()),
                ('Rate', models.TextField()),
                ('Charterer', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'Clarksontimeass',
            },
        ),
        migrations.CreateModel(
            name='errorlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('table', models.TextField()),
            ],
        ),
        migrations.AlterModelTable(
            name='clarksonspotass1',
            table='Clarksonspotass1',
        ),
        migrations.AlterModelTable(
            name='clarksonspotass2',
            table='Clarksonspotass2',
        ),
    ]
