# Generated by Django 2.2.3 on 2019-07-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0009_auto_20190731_1057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='errorlog',
            table='errorlog',
        ),
    ]
