# Generated by Django 2.2.3 on 2019-08-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0010_auto_20190731_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gibsonspotass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mts', models.TextField()),
                ('Country', models.TextField()),
                ('Usperpmt', models.TextField()),
                ('previousweek', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'gibsonspotass',
            },
        ),
        migrations.CreateModel(
            name='Gibsonspotfixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.TextField()),
                ('CBM', models.TextField()),
                ('Mts', models.TextField()),
                ('Cargo', models.TextField()),
                ('Load', models.TextField()),
                ('Disch', models.TextField()),
                ('Laycan', models.TextField()),
                ('Rate', models.TextField()),
                ('Charterer', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'gibsonspotfixture',
            },
        ),
        migrations.CreateModel(
            name='Gibsontimeass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cbm', models.TextField()),
                ('type', models.TextField()),
                ('USperpcm', models.TextField()),
                ('previousweekpcm', models.TextField()),
                ('USperday', models.TextField()),
                ('previousweekday', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'gibsontimeass',
            },
        ),
        migrations.CreateModel(
            name='Gibsontimefixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.TextField()),
                ('CBM', models.TextField()),
                ('Period', models.TextField()),
                ('Delivery', models.TextField()),
                ('Redelivery', models.TextField()),
                ('Laycan', models.TextField()),
                ('Hire', models.TextField()),
                ('Charterer', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'gibsontimefixture',
            },
        ),
    ]
