# Generated by Django 2.2.3 on 2019-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0011_gibsonspotass_gibsonspotfixture_gibsontimeass_gibsontimefixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steemspotass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_mts', models.TextField()),
                ('cargo', models.TextField()),
                ('trade', models.TextField()),
                ('USDperMT', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'steemspotass',
            },
        ),
        migrations.CreateModel(
            name='Steemspotfixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.TextField()),
                ('Built', models.TextField()),
                ('CBM', models.TextField()),
                ('Charterer', models.TextField()),
                ('Qty', models.TextField()),
                ('Cargo', models.TextField()),
                ('LoadPort', models.TextField()),
                ('DischPort', models.TextField()),
                ('Laycan', models.TextField()),
                ('Freight', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'steemspotfixture',
            },
        ),
        migrations.CreateModel(
            name='Steemtimeass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VesselSize', models.TextField()),
                ('HireperUSDpcm', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'steemtimeass',
            },
        ),
        migrations.CreateModel(
            name='Steemtimefixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.TextField()),
                ('Built', models.TextField()),
                ('CBM', models.TextField()),
                ('Charterer', models.TextField()),
                ('Period', models.TextField()),
                ('Cargo', models.TextField()),
                ('DeliveryRedel', models.TextField()),
                ('Laycan', models.TextField()),
                ('Hire', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'steemtimefixture',
            },
        ),
    ]
