# Generated by Django 2.2.3 on 2019-08-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0012_steemspotass_steemspotfixture_steemtimeass_steemtimefixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fearngasspotassement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotmarket', models.TextField()),
                ('Thisweek', models.TextField()),
                ('change', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'fearngasspotassement',
            },
        ),
        migrations.CreateModel(
            name='Fearngasspotfixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.TextField()),
                ('Cbm', models.TextField()),
                ('Type', models.TextField()),
                ('LoadDisch', models.TextField()),
                ('Laycan', models.TextField()),
                ('Rate', models.TextField()),
                ('Charterer', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'fearngasspotfixture',
            },
        ),
        migrations.CreateModel(
            name='Fearngastimefixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.TextField()),
                ('Cbm', models.TextField()),
                ('Period', models.TextField()),
                ('LoadDisch', models.TextField()),
                ('Laycan', models.TextField()),
                ('Rate', models.TextField()),
                ('Charterer', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'fearngastimefixture',
            },
        ),
    ]
