# Generated by Django 2.2.3 on 2019-08-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_extraction', '0013_fearngasspotassement_fearngasspotfixture_fearngastimefixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Braemarspotassesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.TextField()),
                ('price', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Braemarspotfixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Charterer', models.TextField()),
                ('Vessel', models.TextField()),
                ('Cbm', models.TextField()),
                ('YOB', models.TextField()),
                ('Cargo', models.TextField()),
                ('Load', models.TextField()),
                ('Discharge', models.TextField()),
                ('Laycan', models.TextField()),
                ('Rate', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Braemartimeassesment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthTCperpcm_12', models.TextField()),
                ('East', models.TextField()),
                ('West', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Braemartimeassesment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TC', models.TextField()),
                ('pcm', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Braemartimefixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Charterer', models.TextField()),
                ('Vessel', models.TextField()),
                ('Cbm', models.TextField()),
                ('YOB', models.TextField()),
                ('Period', models.TextField()),
                ('Del', models.TextField()),
                ('Redel', models.TextField()),
                ('Laycan', models.TextField()),
                ('Hire', models.TextField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
